//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _11._01_Кол
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dolgnosty
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dolgnosty()
        {
            this.Uchet_inform_o_sotrudnikah = new HashSet<Uchet_inform_o_sotrudnikah>();
        }
    
        public int id_dolgnost { get; set; }
        public string nazvanie { get; set; }
        public decimal oklad { get; set; }
        public string obyazannosti { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Uchet_inform_o_sotrudnikah> Uchet_inform_o_sotrudnikah { get; set; }
    }
}
