//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _11._01_Кол
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class KolEntities : DbContext
    {
        public KolEntities()
            : base("name=KolEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dolgnosty> Dolgnosty { get; set; }
        public virtual DbSet<Oplata> Oplata { get; set; }
        public virtual DbSet<Poochreniya> Poochreniya { get; set; }
        public virtual DbSet<Sotrudniki> Sotrudniki { get; set; }
        public virtual DbSet<Uchet_inform_o_sotrudnikah> Uchet_inform_o_sotrudnikah { get; set; }
    
        public virtual ObjectResult<MaxOplata_Result> MaxOplata()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MaxOplata_Result>("MaxOplata");
        }
    }
}
