//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _11._01_Кол
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oplata
    {
        public int id_oplati { get; set; }
        public int id_naznachenia { get; set; }
        public int id_poochreniya { get; set; }
        public System.DateTime data { get; set; }
    
        public virtual Poochreniya Poochreniya { get; set; }
        public virtual Uchet_inform_o_sotrudnikah Uchet_inform_o_sotrudnikah { get; set; }
    }
}
