//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _11._01_Кол
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uchet_inform_o_sotrudnikah
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Uchet_inform_o_sotrudnikah()
        {
            this.Oplata = new HashSet<Oplata>();
        }
    
        public int id_naznachenia { get; set; }
        public int id_sotrudnika { get; set; }
        public int id_dolgnost { get; set; }
        public System.DateTime data_priema { get; set; }
    
        public virtual Dolgnosty Dolgnosty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Oplata> Oplata { get; set; }
        public virtual Sotrudniki Sotrudniki { get; set; }
    }
}
